Uses the information we have gathered to create a dataset that we will be able to use for our app

In [71]:
# Import libraries
import pandas as pd

In [72]:
# Data 
data = {
    "English speaking": [
        'United Kingdom', 'United States', 'Canada', 'Australia',
        'New Zealand', 'Ireland'
    ],
    "English as second language": [
        "Netherlands", "Denmark", "Sweden", "Norway", "Finland",
        "Luxembourg", "Austria", "Germany", "Poland", "Belgium",
        "Switzerland", "Portugal", "Singapore", "Malaysia", "Philippines"
    ],
    "Safest countries 2025": [
        "Switzerland", "Norway", "Sweden", "Austria", "Denmark",
        "Canada", "Finland", "New Zealand", "Australia", "Belgium",
        "Netherlands", "Ireland", "Iceland", "Luxembourg", "Portugal"
    ],
    "Least racist countries 2026": [
        "Denmark", "Finland", "New Zealand", "Netherlands", "Canada",
        "Belgium", "Sweden", "Norway", "Iceland", "Switzerland",
        "Austria", "Australia", "Ireland", "Luxembourg", "United Kingdom"
    ],
    "Best health care": [
        "Taiwan", "South Korea", "Australia", "Canada", "Sweden",
        "Ireland", "Netherlands", "Germany", "Norway", "Israel",
        "Belgium", "Switzerland", "Japan", "Singapore", "United States"
    ],
    "Wage vs living cost": [
        "Belgium", "Netherlands", "France", "Germany", "Greece",
        "Spain", "Romania", "Luxembourg", "Ireland", "Poland",
        "Slovenia", "Lithuania", "Bulgaria", "Latvia", "Hungary"
    ],
    "Countries with largest Iranians": [
        "United States", "Kuwait", "United Arab Emirates", "Germany",
        "Canada", "Israel", "Bahrain", "Sweden", "Turkey", "France",
        "United Kingdom", "Iraq", "Saudi Arabia", "Australia", "Netherlands"
    ],
    "Highest paying psychologists": [
        "United States", "Denmark", "Switzerland", "Canada", "Ireland",
        "Australia", "Germany", "United Kingdom", "United Arab Emirates",
        "Netherlands"
    ],
    "Top education": [
        "South Korea", "Japan", "Belgium", "Slovenia", "Netherlands",
        "Germany", "Finland", "Norway", "Ireland", "Singapore",
        "France", "China", "Hong Kong", "Sweden"
    ],
    "Best immigrant policies": [
        "New Zealand", "Norway", "Australia", "Canada", "Sweden",
        "Germany", "Luxembourg", "South Korea", "Austria", "Spain",
        "Portugal", "Italy", "Belgium", "Netherlands", "Switzerland"
    ],
    "Top passports": [
        "Singapore", "Japan", "South Korea", "United Arab Emirates",
        "Norway", "Switzerland", "EU", "Malaysia", "United Kingdom",
        "Australia", "Canada", "New Zealand", "Liechtenstein",
        "Iceland", "United States"
    ],
    "Most job opportunities": [
        "New Zealand", "Netherlands", "Iceland", "Australia", "Norway",
        "Switzerland", "Sweden", "Malta", "Denmark", "Ireland"
    ],
    "Migrant acceptance": [
        "Canada", "Iceland", "New Zealand", "Australia", "United States",
        "Sweden", "Ireland"
    ],
    "Best health care cost vs salary": [
        "Luxembourg", "Iceland", "Norway", "Denmark", "Japan",
        "Netherlands", "New Zealand", "Sweden", "United Kingdom",
        "Germany", "France", "Israel", "Australia", "Finland", "Switzerland"
    ],
    "Lowest tolerance drugs": [
        "Sweden", "North Korea", "Japan", "Vietnam", "China", "Iran",
        "Singapore", "Malaysia", "Saudi Arabia", "Indonesia",
        "United Arab Emirates"
    ],
    "Most annual reading": [
        "Norway", "Sweden", "Finland", "Netherlands", "Japan",
        "United Kingdom", "Australia", "United States", "Canada",
        "Germany", "France", "South Korea", "Austria", "Switzerland", "Spain"
    ],
    "Best mental health care": [
        "Sweden", "Germany", "Finland", "France", "Netherlands",
        "Italy", "Canada", "Norway", "Slovenia", "Australia"
    ],
    "Most psychologists per capita": [
        "Argentina", "Costa Rica", "Netherlands", "Guatemala", "Cuba",
        "United States", "Brazil", "Peru", "Greece", "Ecuador"
    ],
    "Healthiest": [
        "Singapore", "Japan", "South Korea", "Taiwan", "China", "Israel",
        "Norway", "Iceland", "Sweden", "Switzerland", "Netherlands",
        "Luxembourg", "Germany", "Hong Kong", "Germany"
    ],
    "Most prosperous": [
        "Norway", "Iceland", "Denmark", "Sweden", "Ireland",
        "Switzerland", "Belgium", "Finland", "Netherlands", "Slovenia",
        "Luxembourg", "Czechia", "Germany", "Australia", "New Zealand"
    ],
    "Best public transport": [
        "France", "Sweden", "Hong Kong", "United States", "Norway",
        "Belgium", "United Kingdom", "Germany", "Argentina", "Spain",
        "Singapore", "Austria", "Australia", "Canada"
    ],
    "Cleanest": [
        "Estonia", "Luxembourg", "Germany", "Finland", "United Kingdom",
        "Sweden", "Norway", "Austria", "Switzerland", "Denmark",
        "Greece", "France", "Netherlands", "Malta", "Belgium"
    ],
    "Pregnancy leave paid above 20 weeks": [
        "Croatia", "United Kingdom", "Australia", "Ireland", "Norway",
        "Slovakia", "Bulgaria", "Czechia", "Poland", "Hungary", "Italy"
    ],
    "Best work life balance": [
        "New Zealand", "Ireland", "Belgium", "Germany", "Norway",
        "Denmark", "Canada", "Australia", "Finland", "Spain",
        "Netherlands", "Portugal", "United Kingdom", "Argentina", "Austria"
    ],
    "Tax above 40 percent": [
        "Finland", "Japan", "Denmark", "Austria", "Sweden",
        "Belgium", "Slovenia", "Netherlands", "Portugal", "Norway",
        "Spain", "Iceland", "China", "Germany", "United Kingdom",
        "France", "South Africa", "South Korea", "Australia",
        "Greece", "Italy", "Ireland"
    ]
}

# EU countries
eu_countries = {
    "Austria", "Belgium", "Bulgaria", "Croatia", "Czechia", "Denmark",
    "Estonia", "Finland", "France", "Germany", "Greece", "Hungary",
    "Ireland", "Italy", "Latvia", "Lithuania", "Luxembourg", "Malta",
    "Netherlands", "Poland", "Portugal", "Romania", "Slovakia", "Slovenia",
    "Spain", "Sweden"
}

In [73]:
continent_map = {
    'Argentina': 'South America', 'Australia': 'Oceania', 'Austria': 'Europe',
    'Bahrain': 'Asia', 'Belgium': 'Europe', 'Brazil': 'South America',
    'Bulgaria': 'Europe', 'Canada': 'North America', 'China': 'Asia',
    'Costa Rica': 'North America', 'Croatia': 'Europe', 'Cuba': 'North America',
    'Czechia': 'Europe', 'Denmark': 'Europe', 'Ecuador': 'South America',
    'Estonia': 'Europe', 'Finland': 'Europe', 'France': 'Europe',
    'Germany': 'Europe', 'Greece': 'Europe', 'Guatemala': 'North America',
    'Hong Kong': 'Asia', 'Hungary': 'Europe', 'Iceland': 'Europe',
    'Indonesia': 'Asia', 'Iran': 'Asia', 'Iraq': 'Asia', 'Ireland': 'Europe',
    'Israel': 'Asia', 'Italy': 'Europe', 'Japan': 'Asia', 'Kuwait': 'Asia',
    'Latvia': 'Europe', 'Liechtenstein': 'Europe', 'Lithuania': 'Europe',
    'Luxembourg': 'Europe', 'Malaysia': 'Asia', 'Malta': 'Europe',
    'Netherlands': 'Europe', 'New Zealand': 'Oceania', 'North Korea': 'Asia',
    'Norway': 'Europe', 'Peru': 'South America', 'Philippines': 'Asia',
    'Poland': 'Europe', 'Portugal': 'Europe', 'Romania': 'Europe',
    'Saudi Arabia': 'Asia', 'Singapore': 'Asia', 'Slovakia': 'Europe',
    'Slovenia': 'Europe', 'South Africa': 'Africa', 'South Korea': 'Asia',
    'Spain': 'Europe', 'Sweden': 'Europe', 'Switzerland': 'Europe',
    'Taiwan': 'Asia', 'Turkey': 'Asia', 'United Arab Emirates': 'Asia',
    'United Kingdom': 'Europe', 'United States': 'North America',
    'Vietnam': 'Asia', 'EU': 'Europe'
}

climate_map = {
    'Argentina': 'Temperate/Arid', 'Australia': 'Arid', 'Austria': 'Temperate',
    'Bahrain': 'Arid', 'Belgium': 'Temperate', 'Brazil': 'Tropical',
    'Bulgaria': 'Cold', 'Canada': 'Cold', 'China': 'Arid',
    'Costa Rica': 'Tropical', 'Croatia': 'Cold', 'Cuba': 'Tropical',
    'Czechia': 'Cold', 'Denmark': 'Cold', 'Dominican Republic': 'Tropical',
    'Ecuador': 'Tropical', 'Estonia': 'Cold', 'Finland': 'Cold',
    'France': 'Temperate', 'Germany': 'Temperate', 'Greece': 'Temperate',
    'Guatemala': 'Tropical', 'Hong Kong': 'Temperate', 'Hungary': 'Cold',
    'Iceland': 'Cold', 'Indonesia': 'Temperate', 'Iran': 'Arid',
    'Iraq': 'Arid', 'Ireland': 'Temperate', 'Israel': 'Arid',
    'Italy': 'Temperate', 'Japan': 'Temperate', 'Kazakhstan': 'Arid',
    'Kuwait': 'Arid', 'Latvia': 'Cold', 'Liechtenstein': 'Cold',
    'Lithuania': 'Cold', 'Luxembourg': 'Temperate', 'Malaysia': 'Tropical',
    'Malta': 'Temperate', 'Mexico': 'Arid', 'Morocco': 'Arid',
    'Netherlands': 'Temperate', 'New Zealand': 'Temperate',
    'North Korea': 'Cold', 'Norway': 'Cold', 'Oman': 'Arid', 'Peru': 'Tropical',
    'Philippines': 'Tropical', 'Poland': 'Cold', 'Portugal': 'Temperate',
    'Qatar': 'Arid', 'Romania': 'Cold', 'Saudi Arabia': 'Arid',
    'Singapore': 'Tropical', 'Slovakia': 'Cold', 'Slovenia': 'Cold',
    'South Africa': 'Arid', 'South Korea': 'Cold', 'Spain': 'Arid',
    'Sweden': 'Cold', 'Switzerland': 'Cold', 'Taiwan': 'Temperate',
    'Thailand': 'Tropical', 'Turkey': 'Arid', 'United Arab Emirates': 'Arid',
    'United Kingdom': 'Temperate', 'United States': 'Temperate',
    'Vietnam': 'Tropical', 'EU': 'Temperate'
}

religion_map = {
    'Argentina': 'Christian', 'Australia': 'Christian', 'Austria': 'Christian',
    'Bahrain': 'Muslim', 'Belgium': 'Christian', 'Brazil': 'Christian',
    'Bulgaria': 'Christian', 'Canada': 'Christian', 'China': 'Unaffiliated',
    'Costa Rica': 'Christian', 'Croatia': 'Christian', 'Cuba': 'Christian',
    'Czechia': 'Unaffiliated', 'Denmark': 'Christian', 'Ecuador': 'Christian',
    'Estonia': 'Unaffiliated', 'Finland': 'Christian', 'France': 'Christian',
    'Germany': 'Christian', 'Greece': 'Christian', 'Guatemala': 'Christian',
    'Hong Kong': 'Unaffiliated', 'Hungary': 'Christian', 'Iceland': 'Christian',
    'Indonesia': 'Muslim', 'Iran': 'Muslim', 'Iraq': 'Muslim',
    'Ireland': 'Christian', 'Israel': 'Jewish', 'Italy': 'Christian',
    'Japan': 'Unaffiliated', 'Kuwait': 'Muslim', 'Latvia': 'Christian',
    'Liechtenstein': 'Christian', 'Lithuania': 'Christian',
    'Luxembourg': 'Christian', 'Malaysia': 'Muslim', 'Malta': 'Christian',
    'Netherlands': 'Christian', 'New Zealand': 'Christian',
    'North Korea': 'Unaffiliated', 'Norway': 'Christian', 'Peru': 'Christian',
    'Philippines': 'Christian', 'Poland': 'Christian', 'Portugal': 'Christian',
    'Romania': 'Christian', 'Saudi Arabia': 'Muslim', 'Singapore': 'Buddhist',
    'Slovakia': 'Christian', 'Slovenia': 'Christian',
    'South Africa': 'Christian', 'South Korea': 'Unaffiliated',
    'Spain': 'Christian', 'Sweden': 'Christian', 'Switzerland': 'Christian',
    'Taiwan': 'Unaffiliated', 'Turkey': 'Muslim',
    'United Arab Emirates': 'Muslim', 'United Kingdom': 'Christian',
    'United States': 'Christian', 'Vietnam': 'Unaffiliated', 'EU': 'Christian'
}

race_map = {
    'Argentina': 'White', 'Australia': 'White', 'Austria': 'Austrian',
    'Bahrain': 'Bahraini', 'Belgium': 'Belgian', 'Brazil': 'White',
    'Bulgaria': 'Bulgarian', 'Canada': 'White', 'China': 'Han Chinese',
    'Costa Rica': 'White/Mestizo', 'Croatia': 'Croat', 'Cuba': 'White',
    'Czechia': 'Czech', 'Denmark': 'Danish', 'Ecuador': 'Mestizo',
    'Estonia': 'Estonian', 'Finland': 'Finn', 'France': 'French',
    'Germany': 'German', 'Greece': 'Greek', 'Guatemala': 'Mestizo',
    'Hong Kong': 'Chinese', 'Hungary': 'Hungarian', 'Iceland': 'Icelandic',
    'Indonesia': 'Javanese', 'Iran': 'Persian', 'Iraq': 'Arab',
    'Ireland': 'Irish', 'Israel': 'Jewish', 'Italy': 'Italian',
    'Japan': 'Japanese', 'Kuwait': 'Kuwaiti', 'Latvia': 'Latvian',
    'Liechtenstein': 'Liechtensteiner', 'Lithuania': 'Lithuanian',
    'Luxembourg': 'Luxembourger', 'Malaysia': 'Malay', 'Malta': 'Maltese',
    'Netherlands': 'Dutch', 'New Zealand': 'White',
    'North Korea': 'Korean', 'Norway': 'Norwegian', 'Peru': 'Mestizo',
    'Philippines': 'Filipino', 'Poland': 'Polish', 'Portugal': 'Portuguese',
    'Romania': 'Romanian', 'Saudi Arabia': 'Arab', 'Singapore': 'Chinese',
    'Slovakia': 'Slovak', 'Slovenia': 'Slovene',
    'South Africa': 'Black African', 'South Korea': 'Korean',
    'Spain': 'Spanish', 'Sweden': 'Swedish', 'Switzerland': 'Swiss',
    'Taiwan': 'Taiwanese', 'Turkey': 'Turkish',
    'United Arab Emirates': 'Emirati', 'United Kingdom': 'White',
    'United States': 'White', 'Vietnam': 'Vietnamese', 'EU': 'European'
}

In [74]:
# Create initial dataframe
all_countries = sorted(set().union(*[set(lst) for lst in data.values()]))

df = pd.DataFrame({'country': all_countries})

df.head()

     country
0  Argentina
1  Australia
2    Austria
3    Bahrain
4    Belgium

In [75]:
# Check if we have duplicates
df.shape[0] == df['country'].nunique()

True

In [76]:
# Create English status
def engish_status(country):
    if country in set(data['English speaking']):
        return 'first'
    elif country in set(data['English as second language']):
        return 'second'
    else:
        return 'not dominant'

df['english_status'] = df['country'].apply(engish_status)

df['english_status'].value_counts()

english_status
not dominant    42
second          15
first            6
Name: count, dtype: int64

In [77]:
df.head()

     country english_status
0  Argentina   not dominant
1  Australia          first
2    Austria         second
3    Bahrain   not dominant
4    Belgium         second

In [78]:
# Safest countries
df['safest'] = df['country'].apply(lambda x: 1 if x in set(data['Safest countries 2025']) else 0)

df['safest'].value_counts()

safest
0    48
1    15
Name: count, dtype: int64

In [79]:
# Least racist
df['least_racist'] = df['country'].apply(lambda x: 1 if x in set(data['Least racist countries 2026']) else 0)

df['least_racist'].value_counts()

least_racist
0    48
1    15
Name: count, dtype: int64

In [80]:
# Best health care
df['best_healthcare'] = df['country'].apply(lambda x: 1 if x in set(data['Best health care']) else 0)

# Wage vs. living cost
df['best_wage_cost_balance'] = df['country'].apply(lambda x: 1 if x in set(data['Wage vs living cost']) else 0)

# Most Iranians
df['most_iranians'] = df['country'].apply(lambda x: 1 if x in set(data['Countries with largest Iranians']) else 0)

# High paying psychology
df['highest_paying_psychology'] = df['country'].apply(lambda x: 1 if x in set(data['Highest paying psychologists']) else 0)

# Top education
df['top_education'] = df['country'].apply(lambda x: 1 if x in set(data['Top education']) else 0)

# Best immigration policies
df['best_immigration_policies'] = df['country'].apply(lambda x: 1 if x in set(data['Best immigrant policies']) else 0)

In [81]:
df.head()

,country,english_status,safest,least_racist,best_healthcare,best_wage_cost_balance,most_iranians,highest_paying_psychology,top_education,best_immigration_policies
0,Argentina,not dominant,0,0,0,0,0,0,0,0
1,Australia,first,1,1,1,0,1,1,0,1
2,Austria,second,1,1,0,0,0,0,0,1
3,Bahrain,not dominant,0,0,0,0,1,0,0,0
4,Belgium,second,1,1,1,1,0,0,1,1

In [82]:
# Passport 
top_passports_explicit = set(data['Top passports']) - {'EU'}

top_passport_set = top_passports_explicit.union(eu_countries)

df['top_passport'] = df['country'].apply(lambda x: 1 if x in top_passport_set else 0)

df['top_passport'].value_counts()

top_passport
1    40
0    23
Name: count, dtype: int64

In [83]:
# Highest job opportunities
df['highest_job_opportunities'] = df['country'].apply(lambda x: 1 if x in set(data['Most job opportunities']) else 0)

# Most migrant acceptance
df['most_migrant_acceptance'] = df['country'].apply(lambda x: 1 if x in set(data['Migrant acceptance']) else 0)

# Best healthcare cost comparing to salary
df['best_healthcare_cost_to_salary'] = df['country'].apply(lambda x: 1 if x in set(data['Best health care cost vs salary']) else 0)

# Lowest tolerance on drugs
df['lowest_tolerance_on_drugs'] = df['country'].apply(lambda x: 1 if x in set(data['Lowest tolerance drugs']) else 0)

# Most annual reading
df['highest_annual_reading_rate'] = df['country'].apply(lambda x: 1 if x in set(data['Most annual reading']) else 0)

# Best mental healthcare
df['best_mental_health_care'] = df['country'].apply(lambda x: 1 if x in set(data['Best mental health care']) else 0)

# Most psychologists per capita
df['most_psychologists_per_capita'] = df['country'].apply(lambda x: 1 if x in set(data['Most psychologists per capita']) else 0)

# Healthiest 
df['healthiest'] = df['country'].apply(lambda x: 1 if x in set(data['Healthiest']) else 0)

# Most prosperous 
df['most_prosperous'] = df['country'].apply(lambda x: 1 if x in set(data['Most prosperous']) else 0)

# Best public transport
df['best_public_transport'] = df['country'].apply(lambda x: 1 if x in set(data['Best public transport']) else 0)

# Cleanest
df['cleanest'] = df['country'].apply(lambda x: 1 if x in set(data['Cleanest']) else 0)

# Pregnancy leave paid above 20 weeks
df['pregnancy_leave_above_20_weeks'] = df['country'].apply(lambda x: 1 if x in set(data['Pregnancy leave paid above 20 weeks']) else 0)

# Best work life balance
df['best_work_life_balance'] = df['country'].apply(lambda x: 1 if x in set(data['Best work life balance']) else 0)

# Tax above 40 percent
df['tax_above_40_percent'] = df['country'].apply(lambda x: 1 if x in set(data['Tax above 40 percent']) else 0)

df.head()

,country,english_status,safest,least_racist,best_healthcare,best_wage_cost_balance,most_iranians,highest_paying_psychology,top_education,best_immigration_policies,...,highest_annual_reading_rate,best_mental_health_care,most_psychologists_per_capita,healthiest,most_prosperous,best_public_transport,cleanest,pregnancy_leave_above_20_weeks,best_work_life_balance,tax_above_40_percent
0,Argentina,not dominant,0,0,0,0,0,0,0,0,...,0,0,1,0,0,1,0,0,1,0
1,Australia,first,1,1,1,0,1,1,0,1,...,1,1,0,0,1,1,0,1,1,1
2,Austria,second,1,1,0,0,0,0,0,1,...,1,0,0,0,0,1,1,0,1,1
3,Bahrain,not dominant,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Belgium,second,1,1,1,1,0,0,1,1,...,0,0,0,0,1,1,1,0,1,1

In [84]:
# Add cat columns
df['continent'] = df['country'].map(continent_map)
df['climate'] = df['country'].map(climate_map)
df['religion'] = df['country'].map(religion_map)
df['race'] = df['country'].map(race_map)

# New head
df.head()

,country,english_status,safest,least_racist,best_healthcare,best_wage_cost_balance,most_iranians,highest_paying_psychology,top_education,best_immigration_policies,...,most_prosperous,best_public_transport,cleanest,pregnancy_leave_above_20_weeks,best_work_life_balance,tax_above_40_percent,continent,climate,religion,race
0,Argentina,not dominant,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,South America,Temperate/Arid,Christian,White
1,Australia,first,1,1,1,0,1,1,0,1,...,1,1,0,1,1,1,Oceania,Arid,Christian,White
2,Austria,second,1,1,0,0,0,0,0,1,...,0,1,1,0,1,1,Europe,Temperate,Christian,Austrian
3,Bahrain,not dominant,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,Asia,Arid,Muslim,Bahraini
4,Belgium,second,1,1,1,1,0,0,1,1,...,1,1,1,0,1,1,Europe,Temperate,Christian,Belgian

In [85]:
df.to_csv('countries_dataset.csv', index = False)